name: M2 Coding Standard
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static:
    name: M2 Coding Standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: MAD-I-T/magento-actions@master
        with:
          php: '7.4'
          process: 'phpcs-test'
          extension: '.'
          standard: 'Magento2'
